version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-example-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1470t6w5d5c2f"
s3_prefix = "aws-sam-example-python"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
